server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://productapi:8081
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /api/product/$\{segment}
        - id: order-service
          uri: http://orderapi:8080
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /api/order/$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
